version: '2.1'
services:
  mariadb:
    image: mariadb:5.5.60
    container_name: RO_DB
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./ROEmulator/usr/local/mysql/my.cnf:/etc/mysql/conf.d/ro.cnf
      - ./ROEmulator/usr/local/mysql/data:/var/lib/mysql
    ports: 
      - 3306:3306
    networks: 
      vpn:
        ipv4_address: 172.168.99.2
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10


  apache:
    container_name: RO_WEB
    build: 
      context: ./ROEmulator/docker/apache2
      dockerfile: ./Dockerfile
    volumes:
      - ./ROEmulator/docker/apache2/httpd.conf:/etc/apache2/apache2.conf
      - ./ROEmulator/docker/apache2/logs:/var/log/apache2/logs
      - ./ROEmulator/docker/apache2/www:/var/www/html
    ports: 
      - 8096:8096
    depends_on:
      mariadb:
        condition: service_healthy
    networks: 
      vpn:
        ipv4_address: 172.168.99.3


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.99.0/24
          gateway: 172.168.99.1